### ISSUE TITLE
Is possible use this bundle in Sonata Admin?

### ISSUE THREAD

**Issue by amadohin** [prestaconcept/PrestaImageBundle#20]
Is there anyway to use this bundle with Sonata Admin?

**Comment by J-Ben87** [comment]
I didn't try yet but I don't see any reasons it wouldn't work.

**Comment by amadohin** [comment]
I have tried but I can't get the modal open in the admin section.

I don't know how exactly import the template in admin section, and I don't know how to add the javascript for cropper in admin section.

Help.

**Comment by J-Ben87** [comment]
Hi,

I had to use this bundle for a project this week-end and it turns out that there were a few issues. Among others I ran into the same issue as you: I couldn't get the modal opened.

I made a few fixes that might help. At least it solved my issues.

For the record, the modal which was not showing was due to an old JS way to export our Cropper implementation. I'm using webpack so I updated it to be compliant with commonjs and it's working now.

Let me know if you keep having trouble.
