### ISSUE TITLE
missing bootstrap modal ... :-(

### ISSUE THREAD

**Issue by treeindark** [prestaconcept/PrestaImageBundle#92]
@PrestaImage/form/bootstrap_5.html.twig was deleted!!!!

**Comment by J-Ben87** [comment]
Hi.
Do not panic, be polite.

Indeed there is no CHANGELOG file in this bundle, I don't have time to maintain it. However [the README.md is up to date](https://github.com/prestaconcept/PrestaImageBundle#configuration) and you'll find that the template has been renamed `form_layout.html.twig`.

**Comment by treeindark** [comment]
No Problemo J-Ben87, just surprise after an update.

form_layout.html.twig do not use de bootstrap modal, and cropper.js too

**Comment by J-Ben87** [comment]
The renaming is related to [this commit](https://github.com/prestaconcept/PrestaImageBundle/commit/db54576853106d0d2c000da347387ddb13be5aae). The idea was to stop relying on external libraries, especially some that are getting abandonned by more and more people.

However you can create your own form layout to implement bootstrap styles if you really want to :wink:

**Comment by nicodemuz** [comment]
Is there any code shipped by default that makes the default look and feel like a modal? I just see a div that renders below the input box, is this expected behaviour?

**Comment by J-Ben87** [comment]
Hi,

Indeed this is the expected behavior since I dropped Bootstrap support.

This bundle aims to provide tools to ease the development of an image upload and cropping system, but IMHO it should not come with a predefined look and feel that will pretty much **not** match your web app requirements.
However it should be pretty easy to turn the `<div class="presta-image-modal">` into a modal if you want to, or simply style it as a block component that may fade in/out below the form.

However if you feel like it would be more convenient to have a default modal style shipped with the bundle, feel free to open an issue and a PR so that we can discuss the best way to achieve that :slightly_smiling_face:
